#!/bin/bash
#SBATCH --job-name=SeqsXlocus     ## job name
#SBATCH -e SeqsXlocus_%j.e.txt    ## error message name
#SBATCH -o SeqsXlocus.log.%j.out  ## log file output name
#SBATCH --mail-user=phillip.morin@noaa.gov
#SBATCH --mail-type=ALL  ## (NONE, BEGIN, END, FAIL, ALL)
#SBATCH -p medmem
#SBATCH -c 1
#SBATCH --ntasks=1
#SBATCH -D /scratch/pmorin/temp		## <folder to change to when starting the job>

#######################
#The script loops through each line of the text file and uses grep to find the matching headers in the fasta file. The -A 1 option tells grep to also print the next line (which will be the sequence) after each matched header. The output is then appended to the output file.

#variables
CONDIR=/home/pmorin/projects/Miscellaneous/Delphinidae_UCE
INDIR=${CONDIR}/UCE_loci_out_stringent
cd $INDIR
OUTDIR=${CONDIR}/aligned_loci_out6
mkdir -p ${OUTDIR}

# Replace "textfile.txt" with the name of your text file
BW_LOC=${INDIR}/"Delph_UCE_loc_list_stringent.txt" #TEXTFILE="textfile.txt"
#This is just the "description" column from the bed file, in a text file.

####################################################################################
dos2unix $BW_LOC # this is needed because the text file has returns that are being included in the array. This converts dos returns to unix returns so they aren't included.

# Replace "fastalist.txt" with the name of the file that lists all the fasta files you want to search
ls -1 ${INDIR}/*bedout.fa > ${INDIR}/Ziph_bedout.fa_list.txt
# this is a list of fasta files containing the selected sequences from each species, generated by the script "BW_extract_genes_array_Sedna.sh"
BW_SEQ="Ziph_bedout.fa_list.txt" #FASTALIST="fastalist.txt"

# Read each line of the text file into an array
#IFS=$'\n' read -d '' -r -a TEXTARRAY < $BW_LOC #$TEXTFILE
mapfile -t TEXTARRAY < $BW_LOC
# echo ${TEXTARRAY[@]}

# readarray -t TEXTARRAY < $BW_LOC
# Loop through each fasta file in the list (=FASTAFILE in list) to copy sequences to output file for each locus.
while read -r FASTAFILE
do
    # Loop through each line of the text file
    for i in "${!TEXTARRAY[@]}"
    do
    OUTFILE="Loc_$i.fasta"
    echo $OUTFILE
    echo $FASTAFILE
    echo "${TEXTARRAY[i]}"
        # Find the matching headers in the fasta file and copy matching headers and following line (sequence) to the output file
        grep -A 1 "${TEXTARRAY[i]}:" $FASTAFILE >> ${OUTDIR}/$OUTFILE #$OUTPUTFILE
    done
done < $INDIR/$BW_SEQ # $FASTALIST

#Note that this script assumes that each line of the text file contains a unique string that should be used to match fasta headers. If the text file contains multiple lines with the same string, the script will copy the corresponding fasta headers and sequences multiple times to the output file. If you need to ensure that each fasta header is only included once in the output file, you'll need to modify the script to remove duplicates.

# checking that textarray is correct
# for LINE in "${TEXTARRAY[@]}"; do echo $LINE; done
# for i in "${TEXTARRAY[@]}"; do OUTFILE="$i"; echo "$OUTFILE"; done
# for i in "${BW_LOC}"; do OUTFILE="$i"; echo "$OUTFILE"; done